include config.inc

LDFLAGS=-fPIC
CFLAGS=-Wall -I$(SRC)

ifeq ($(REL),debug)
CFLAGS+=-g
endif

FORKER=$(BINDIR)/wf_forker

all: $(FORKER)

$(FORKER): src/utils/forker.c
	gcc -o $(FORKER) src/utils/forker.c -Isrc $(CFLAGS) $(LDFLAGS) -L$(BINDIR) -lwf_commline

clean:
	rm -rf $(FORKER)
