include config.inc

LDFLAGS=-fPIC -lpthread
CFLAGS=-Wall

ifeq ($(REL),debug)
CFLAGS+=-g
endif

UTIL=src/utils
SRC=$(UTIL)/forker.c $(UTIL)/monitor.c $(UTIL)/pty_handler.c
FORKER=$(BINDIR)/wf_forker
UDP_CMD=$(BINDIR)/udp_cmd

all: $(FORKER) $(UDP_CMD)

$(FORKER): $(SRC)
	gcc -o $(FORKER) $(SRC) -Isrc $(CFLAGS) $(LDFLAGS) -L$(BINDIR) -lwf_commline -lutil

$(UDP_CMD): $(UTIL)/udp_cmd.c
	gcc -o $(UDP_CMD) $(UTIL)/udp_cmd.c

clean:
	@rm -f $(FORKER) $(UDP_CMD)
